name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run tests with coverage
      id: coverage
      run: |
        go test -coverprofile=coverage.out ./...
        COVERAGE=$(go tool cover -func=coverage.out | tail -1 | awk '{print $3}' | sed 's/%//')
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Coverage: $COVERAGE%"
    
    - name: Update README with coverage badge
      run: |
        COVERAGE=${{ steps.coverage.outputs.coverage }}
        # Create dynamic badge URL
        BADGE_URL="https://img.shields.io/badge/Coverage-${COVERAGE}%25-brightgreen"
        
        # Update README.md with new badge
        sed -i "s|\[!\[Coverage\].*\]|\[!\[Coverage\](${BADGE_URL})\]|g" README.md
        
        # Commit and push changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update coverage badge to ${COVERAGE}%" || exit 0
        git push 